apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: portal-noticias
  
spec:
  containers:
  - name: porta-noticias-container
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80
